FROM arm32v7/python:3.7-slim-buster

RUN apt-get update

RUN apt-get upgrade 

RUN apt-get install gcc build-essential python3-dev git -y

RUN apt-get install python3-gpiozero -y

RUN git clone https://github.com/adafruit/Adafruit_Python_DHT.git
WORKDIR /Adafruit_Python_DHT

RUN python3 setup.py install

WORKDIR /app

COPY requirements.txt ./
RUN pip install -r requirements.txt

COPY . .

CMD [ "python3", "-u", "./main.py" ]